services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-application
    environment:
      - PORT=80
      - DOCKER_BUILDKIT=1
      - DEEPL_KEY=<insert your DeepL API key>
      - SERVER_URL=<insert your domain here>
    ports:
      - 80:80
    command:
      ["uvicorn", "app:app", "--host", "0.0.0.0", "--reload", "--port", "80"]
    restart: "no"
